'use client';import{useState}from'react';
const care=[['Saúde hormonal','Avaliação individualizada para compreender sintomas, fases hormonais e qualidade de vida.'],['Menopausa','Cuidado para atravessar mudanças com mais energia, equilíbrio e bem-estar.'],['Endometriose','Investigação e acompanhamento atento às particularidades de cada mulher.'],['Emagrecimento','Estratégia clínica que considera metabolismo, hormônios, rotina e objetivos.'],['Ginecologia regenerativa','Tecnologias e protocolos voltados à saúde íntima e ao conforto feminino.'],['Laser CO₂','Tratamento indicado após avaliação médica individualizada.'],['Lipedema','Plano integrativo que considera inflamação, hormônios, hábitos e tecnologias.'],['Saúde hormonal masculina','Cuidado clínico para energia, composição corporal e longevidade.']];
export default function Home(){const[menu,setMenu]=useState(false);return <main><header><a className="logo" href="#inicio"><b>F</b><span>FEMINE<small>SAÚDE HORMONAL</small></span></a><nav className={menu?'open':''}><a href="#conceito" onClick={()=>setMenu(false)}>A Femine</a><a href="#cuidados" onClick={()=>setMenu(false)}>Tratamentos</a><a href="#flavia" onClick={()=>setMenu(false)}>Dra. Flávia</a><a href="#contato" onClick={()=>setMenu(false)}>Contato</a></nav><a className="book" href="https://wa.me/5594991624490" target="_blank">Agendar avaliação ↗</a><button onClick={()=>setMenu(!menu)}>{menu?'FECHAR':'MENU'}</button></header>
<section className="hero" id="inicio"><div className="heroHalo"><i/><i/><i/></div><div className="heroPhoto"/><div className="heroCopy"><p>FEMININO & MASCULINO · PARAUAPEBAS</p><h1>Seu corpo<br/>fala. A gente<br/><em>escuta.</em></h1><div><span>SAÚDE HORMONAL</span><p>Um cuidado integrativo, ético e baseado em evidências para você recuperar energia, equilíbrio e qualidade de vida.</p></div></div><div className="heroStamp"><b>F</b><small>CUIDADO<br/>INDIVIDUALIZADO</small></div><a className="scroll" href="#conceito">CONHEÇA A FEMINE ↓</a></section>
<section className="opening" id="conceito"><span>01</span><div><p>NÃO É SÓ SOBRE SINTOMAS.</p><h2>É sobre voltar<br/>a se <em>reconhecer.</em></h2></div><p>Cansaço, alterações no sono, libido, peso ou humor não devem ser normalizados. Na Femine, cada paciente é avaliado de forma personalizada, respeitando sua história, seus sintomas e sua fase hormonal.</p></section>
<section className="bodyMap"><div className="mapCopy"><p>UM OLHAR PARA O TODO</p><h2>Equilíbrio acontece<br/>quando os pontos<br/><em>se conectam.</em></h2><ul><li><i/> Hormônios</li><li><i/> Metabolismo</li><li><i/> Sono e energia</li><li><i/> Saúde íntima</li><li><i/> Composição corporal</li><li><i/> Longevidade</li></ul></div><div className="mapVisual"><div className="silhouette"/><span className="point p1">HORMÔNIOS</span><span className="point p2">ENERGIA</span><span className="point p3">METABOLISMO</span><span className="point p4">BEM-ESTAR</span><div className="scan"/></div></section>
<section className="care" id="cuidados"><div className="careHead"><p>02 — FRENTES DE CUIDADO</p><h2>Para cada fase,<br/>um cuidado <em>preciso.</em></h2></div><div className="careIndex">{care.map((x,i)=><article key={x[0]}><span>{String(i+1).padStart(2,'0')}</span><h3>{x[0]}</h3><p>{x[1]}</p><i>↗</i></article>)}</div></section>
<section className="life"><div className="lifeTitle"><p>03 — SAÚDE FEMININA</p><h2>O corpo muda.<br/>O cuidado <em>evolui.</em></h2></div><div className="timeline"><i/><article><b>01</b><h3>Ciclos</h3><p>Saúde ginecológica e hormonal para compreender sinais e prevenir desequilíbrios.</p></article><article><b>02</b><h3>Planos</h3><p>Fertilidade, sexualidade e escolhas acompanhadas com informação e segurança.</p></article><article><b>03</b><h3>Transições</h3><p>Climatério e menopausa com cuidado individualizado e qualidade de vida.</p></article><article><b>04</b><h3>Longevidade</h3><p>Força, massa muscular, autonomia e saúde para os próximos capítulos.</p></article></div></section>
<section className="doctor" id="flavia"><div className="doctorPhoto"><span>MEDICINA COM PROPÓSITO</span></div><div className="doctorCopy"><p>DRA. FLÁVIA ALVES</p><h2>Ciência para cuidar.<br/><em>Escuta para compreender.</em></h2><p>Meu propósito é cuidar da saúde feminina de forma integrativa, ética e baseada em evidências. Cada avaliação começa pela história da paciente e considera sintomas, fase hormonal, rotina e objetivos.</p><blockquote>“Você não precisa viver cansada, sem energia e sem se reconhecer.”</blockquote><a href="https://wa.me/5594991624490" target="_blank">AGENDAR CONSULTA ↗</a></div></section>
<section className="principles"><div><span>01</span><h3>Individualização</h3><p>Nenhum corpo é igual ao outro. O plano de cuidado também não deve ser.</p></div><div><span>02</span><h3>Integração</h3><p>Sintomas, exames, hábitos e história vistos como partes do mesmo todo.</p></div><div><span>03</span><h3>Evidência</h3><p>Decisões clínicas responsáveis, com indicação e acompanhamento médico.</p></div></section>
<section className="contact" id="contato"><div className="contactMedia"/><div className="contactCopy"><p>COMECE PELO PRIMEIRO PASSO</p><h2>Seu cuidado<br/>pode começar<br/><em>agora.</em></h2><a href="https://wa.me/5594991624490?text=Olá!%20Gostaria%20de%20agendar%20uma%20avaliação%20na%20Clínica%20Femine." target="_blank">FALAR COM A FEMINE <span>↗</span></a><address><small>ENDEREÇO</small><p>Galeria Parque dos Carajás<br/>Av. Potiguá, Qd. 08, Lt. 18 · Térreo<br/>Parque dos Carajás · Parauapebas — PA</p><a href="tel:+5594991624490">(94) 99162-4490</a></address></div></section>
<footer><a className="logo" href="#inicio"><b>F</b><span>FEMINE<small>SAÚDE HORMONAL</small></span></a><p>© 2026 · Clínica Femine</p><a href="https://www.instagram.com/femine.clinica/" target="_blank">Instagram ↗</a></footer><a className="wa" href="https://wa.me/5594991624490" target="_blank" aria-label="WhatsApp">WA</a></main>}
